version: '3.8'
services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test1234!
    ports:
      - '6000:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
